# Sample YAML script to test Action

name: testscript

on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Current time
        run: echo "The current date and time is" $(date)
